<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.paypulse</groupId>
    <artifactId>paypulse</artifactId>
    <version>1.0.1-SNAPSHOT</version>
  </parent>

  <artifactId>merchant-domain</artifactId>

  
  <dependencies>
    <dependency>
      <groupId>com.paypulse</groupId>
      <artifactId>merchant-model</artifactId>
      <version>1.0.1-SNAPSHOT</version>
    </dependency>
      <dependency>
          <groupId>org.projectlombok</groupId>
          <artifactId>lombok</artifactId>
      </dependency>
      <dependency>
          <groupId>org.mapstruct</groupId>
          <artifactId>mapstruct</artifactId>
      </dependency>
  </dependencies>

</project>
